Feature/ffa3ecf/create list size instruction
metadew/iesi pull request #313
Opened 2021-04-08 10:12 UTC by Suyash-d

Hi Robbe,
Please review changes for newly added ListSize instruction

2021-04-08 11:20 UTC, BerrevoetsRobbe requested changes

2021-04-08 11:20 UTC, BerrevoetsRobbe commented on core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/ExecutionRuntime.java
> +        dataInstructions = DataInstructionRepository.getRepository(new GenerationObjectExecution(),this);
code formatting. you can auto-format the code using IntelliJ.
Normally the Sonarlint plugin will also complain about this.

2021-04-08 11:20 UTC, BerrevoetsRobbe commented on core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/DataInstructionRepository.java
> +        dataInstructions.put(listSize.getKeyword(),listSize);
code formatting. you can auto-format the code using IntelliJ.
Normally the Sonarlint plugin will also complain about this.

2021-04-08 11:20 UTC, BerrevoetsRobbe commented on core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/date/ListSize.java
> +                    .orElseThrow(() -> new IllegalArgumentException(MessageFormat.format("No array found", ((Text) array).getString())));
replace `MessageFormat.format("No array found", ((Text) array).getString()))` with `String.format("No array %s found in memory", ((Text) array).getString()))`

2021-04-08 11:20 UTC, BerrevoetsRobbe commented on core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/date/ListSizeTest.java
> +        ExecutionRuntime executionRuntime = mock(ExecutionRuntime.class);
Have a look online on @Before and @After for unit tests. This recurring block can be put in setup and teardown methods for the tests

2021-04-08 11:20 UTC, BerrevoetsRobbe commented on core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/date/ListSizeTest.java
> +        Whitebox.setInternalState(DataTypeHandler.class, "instance", (DataTypeHandler) null);
Have a look online on @Before and @After for unit tests. This recurring block can be put in setup and teardown methods for the tests

2021-04-08 11:20 UTC, BerrevoetsRobbe commented on core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/date/ListSizeTest.java
> +        assertThrows(IllegalArgumentException.class, () -> listSize.generateOutput(null));
Can you also check the Exception message?

2021-04-08 11:20 UTC, BerrevoetsRobbe commented on core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/date/ListSizeTest.java
> +    public void generateOutputWithText() {
Add a similar test where the array with name "array" is not found in memory (so ExecutionRuntime#getArray return an Optional.empty() )

2021-04-08 11:21 UTC, BerrevoetsRobbe requested changes

2021-04-08 11:21 UTC, BerrevoetsRobbe commented on core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/date/ListSizeTest.java
> +public class ListSizeTest {
code formatting. 
public can be removed, normally the SonarLint plugin complains about this

2021-04-08 11:21 UTC, BerrevoetsRobbe commented on core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/date/ListSizeTest.java
> +    public void getKeyword() {
code formatting. 
public can be removed, normally the SonarLint plugin complains about this.

2021-04-08 12:36 UTC, Suyash-d reviewed
Review Changes Added

2021-04-12 07:29 UTC, BerrevoetsRobbe commented on core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/date/ListSizeTest.java
> +        assertThrows(IllegalArgumentException.class, () -> listSize.generateOutput(null));
@Suyash-d reminder

2021-04-12 10:57 UTC, BerrevoetsRobbe requested changes

2021-04-12 10:57 UTC, BerrevoetsRobbe commented on core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/date/ListSizeTest.java
> +        assertThat(exception.getMessage()).isEqualTo("list cannot be of type class io.metadew.iesi.datatypes._null.Null");
you can combine these tests using assertJ
https://www.baeldung.com/assertj-exception-assertion

2021-04-12 10:57 UTC, BerrevoetsRobbe commented on core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/date/ListSizeTest.java
> +        assertThat(exception.getMessage()).isEqualTo("No array array found in memory");
you can combine these tests using assertJ
https://www.baeldung.com/assertj-exception-assertion

2021-04-12 10:57 UTC, BerrevoetsRobbe commented on core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/date/ListSizeTest.java
> +
on line 37: is the class variable `listSize` ever used?
If not, can you remove it?

2021-04-12 12:57 UTC, Suyash-d reviewed
Requested Review Changes Added

2021-04-12 13:44 UTC, BerrevoetsRobbe approved these changes
approved

2021-04-12 13:44 UTC, merged