Create Component-Types controller
metadew/iesi pull request #317
Opened 2021-04-14 13:40 UTC by hkhattabii

Able the iesi web appplication to fetch the component-types

2021-04-14 15:00 UTC, BerrevoetsRobbe requested changes

2021-04-14 15:00 UTC, BerrevoetsRobbe commented on core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/componentTypes/ComponentTypeDtoService.java
> +}
can't this be put in a ResourceAssembler?

2021-04-14 15:00 UTC, BerrevoetsRobbe commented on core/java/iesi-rest-without-microservices/src/main/resources/application-iesi-connection-types.yml
> +            mandatory: true
this is not mandatory

2021-04-15 07:37 UTC, hkhattabii commented on core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/componentTypes/dto/ComponentTypeParameterService.java
> +}
It is not possible to add resource assembler support for the ComponentTypeParameterDto.
The ComponentTypeParameter doesn't have the name getter, so I had to pass the nam as an argument.
Also,  the RepresentationModelAssemblerSupport doesn't provide the methods ToModel with a second argument.

So I let the service to convert the ComponentTypeParameter to Dto

2021-04-16 07:59 UTC, BerrevoetsRobbe requested changes

2021-04-16 07:59 UTC, BerrevoetsRobbe commented on core/java/iesi-core/src/main/java/io/metadew/iesi/common/configuration/metadata/componenttypes/MetadataComponentTypesConfiguration.java
> +import io.metadew.iesi.metadata.definition.connection.ConnectionType;
unused import?

2021-04-16 07:59 UTC, BerrevoetsRobbe commented on core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/componentTypes/dto/ComponentTypeDtoResourceAssembler.java
> +                        .collect(Collectors.toList())
Move logic of core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/componentTypes/dto/ComponentTypeParameterService.java to here and remove core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/componentTypes/dto/ComponentTypeParameterService.java

2021-04-19 07:54 UTC, BerrevoetsRobbe commented on core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/componentTypes/dto/ComponentTypeDtoResourceAssembler.java
> +                        .collect(Collectors.toList())
bump

2021-04-20 08:50 UTC, BerrevoetsRobbe approved these changes

2021-04-20 08:51 UTC, merged